### PR TITLE
Gulpfile changes

### PR DESCRIPTION
**Pull request by thejameskyle**
- Uses gulpfile.babel.js
- Bumps gulp
- Starts to use ES6

Finally I also started moving all the contents of tasks into functions. There's more refactoring work to do here, but you'll notice that there's a bunch of extra tasks that people create when writing gulp when you can actually just use normal functions. I started the work of moving things over like this:

```js
function clean(dir, cb) {
  del([dir], cb);
}

gulp.task('clean', done => clean(destinationFolder, done));
gulp.task('clean-tmp', done => clean('tmp', done));
```

Again, more refactoring can be done here, but for now everything lives within separate functions than their tasks.

### CODE REVIEW

**Comment by thejameskyle** [comment]
Hmm, for some reason istanbul is getting all upset

**Comment by thejameskyle** [comment]
Opened an issue in Babel

**Comment by jmeas** [comment]
Sry, updated the Gulpfile this morning @thejameskyle :speak_no_evil:

**Comment by jmeas** [comment]
@thejameskyle want to split this out into smaller, easier-to-merge PRs? This is good stuff.

**Comment by jmeas** [comment]
ping @thejameskyle

**Comment by jmeas** [comment]
Opened two issues for the changes here: #211 and #212

**Pull request closed without merging**
