### PR TITLE
Improve Gulpfile

### LINKED ISSUE #211: Use gulpfile.babel.js

### PR DESCRIPTION
**Pull request by thejameskyle**
Resolves #211, #212

### CODE REVIEW

**Comment by thejameskyle** [comment]
Don't merge yet, working on this

**Comment by thejameskyle** [comment]
Good to go

**Comment by jmeas** [comment]
Yessss! Thanks @thejameskyle . I'll review this later today

**Comment by thejameskyle** [comment]
@jmeas after this we should have a discussion about how to make it so that people can modify their gulpfile and manage to stay up to date with changes to the generator.

**Comment by jmeas** [comment]
Sounds good. Sorry I didn't get a chance to review this yesterday, sis was in town. Will merge 2night

**Pull request merged**
